[[km]]
name = "得力 树脂鼠标垫"
desc = "耐磨、防水、易清洗的树脂鼠标垫"
size = 2569
[[km]]
name = "雷蛇 毒蝰迷你版"
desc = "百元内性能最佳的鼠标、61克轻量化设计、适合中小手"
size = 1175
[[km]]
name = "罗技 G102"
desc = "流光灯效、鼠标宏、可自定义DPI的多功能鼠标"
size = 1836
[[km]]
name = "京造键盘 C2 茶轴"
desc = "多设备兼容的标准键盘"
size = 2548
[[km]]
name = "京造键盘 K1 茶轴"
desc = "多连接方式、多设备兼容的矮键盘"
size = 2352
[[hs]]
name = "飞利浦 SPA20"
desc = "3.5mm接口、2.0声道的小型音响，音质在200元以下没有敌手"
size = 2748
[[hs]]
name = "飞利浦 SHP9500"
desc = "3.5mm接口的头戴式无麦克风耳机，音质在500元以下没有敌手"
size = 4067
[[ar]]
name = "铁三角 ATR2500"
desc = "USB接口的电容麦克风，声音清澈，对环境安静要求高"
size = 2404
